import json

from ollama import chat

from llm_judge.decorator import (
    llm_metrics,
    agent_metrics
)


class LLMJudge:

    def __init__(self, model="mistral"):
        self.model = model

    # ==================================================
    # Generate the response
    # ==================================================

    @agent_metrics
    def generate_agent_response(
        self,
        prompt: str,
        agent_name: str = "Test Agent"
    ):

        result = chat(
            model=self.model,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        response = result["message"]["content"]

        input_tokens = result.get(
            "prompt_eval_count",
            0
        )

        output_tokens = result.get(
            "eval_count",
            0
        )

        return {
            "agent_name": agent_name,
            "prompt": prompt,
            "response": response,
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "total_tokens": input_tokens + output_tokens,
            "model": self.model
        }

    # ==================================================
    # Judge the response
    # ==================================================

    @llm_metrics
    def evaluate(
        self,
        agent_name: str,
        prompt: str,
        response: str
    ):

        judge_prompt = f"""
You are an LLM evaluator.

You are evaluating the response generated by an AI agent.

Agent Name:
{agent_name}

Original Prompt:
{prompt}

Agent Response:
{response}

Evaluate the response on the following:

1. Correctness
2. Relevance
3. Completeness
4. Clarity
5. Overall Quality

Give a score from 0 to 10 for each.

Return ONLY valid JSON.

Do not use markdown.
Do not use ```json.
Do not write anything outside the JSON.

Use exactly this structure:

{{
    "correctness": {{
        "score": 0,
        "explanation": ""
    }},
    "relevance": {{
        "score": 0,
        "explanation": ""
    }},
    "completeness": {{
        "score": 0,
        "explanation": ""
    }},
    "clarity": {{
        "score": 0,
        "explanation": ""
    }},
    "overall": {{
        "score": 0,
        "explanation": ""
    }}
}}
"""

        result = chat(
            model=self.model,
            messages=[
                {
                    "role": "user",
                    "content": judge_prompt
                }
            ]
        )

        raw_response = result["message"]["content"]

        try:
            judge_response = json.loads(raw_response)

        except json.JSONDecodeError:

            judge_response = {
                "correctness": {
                    "score": 0,
                    "explanation": "Unable to parse Judge response."
                },
                "relevance": {
                    "score": 0,
                    "explanation": "Unable to parse Judge response."
                },
                "completeness": {
                    "score": 0,
                    "explanation": "Unable to parse Judge response."
                },
                "clarity": {
                    "score": 0,
                    "explanation": "Unable to parse Judge response."
                },
                "overall": {
                    "score": 0,
                    "explanation": raw_response
                }
            }

        input_tokens = result.get(
            "prompt_eval_count",
            0
        )

        output_tokens = result.get(
            "eval_count",
            0
        )

        return {
            "model": self.model,
            "agent_name": agent_name,
            "prompt": prompt,
            "agent_response": response,
            "judge_response": judge_response,
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "total_tokens": input_tokens + output_tokens
        }